package history

import "time"

// Workout represents a single workout session from Hevy
type Workout struct {
	ID          string    `json:"id"`
	WorkoutName string    `json:"workout_name"`
	Date        time.Time `json:"date"`
	Duration    int       `json:"duration"` // in seconds
	Exercises   []Exercise `json:"exercises"`
	Notes       string    `json:"notes"`
	HevyID      string    `json:"hevy_id"` // Unique ID from Hevy
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

// Exercise represents a single exercise within a workout
type Exercise struct {
	ID          string  `json:"id"` // This ID will be generated by our system
	ExerciseName string `json:"exercise_name"`
	Sets        []Set   `json:"sets"`
	Notes       string  `json:"notes"`
}

// Set represents a single set within an exercise
type Set struct {
	ID      string  `json:"id"` // This ID will be generated by our system
	Weight  float64 `json:"weight"`
	Reps    int     `json:"reps"`
	RPE     float64 `json:"rpe"` // Rate of Perceived Exertion
}
